<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDAR592T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDAR592T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDAR592T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDAR592T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDAR592T\App_KernelDevDebugContainer([
    'container.build_hash' => 'DAR592T',
    'container.build_id' => 'eab15bb7',
    'container.build_time' => 1588878957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDAR592T');
